import { Inter } from "next/font/google";
import "./globals.css";
import { LeftSideBar } from "@/components/partials/leftsidebar";
import Image from "next/image";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section>
          <div className="h-screen flex">
            <LeftSideBar />
            <div className="w-full">
              {/* <Image src={Top_Img} className="w-full h-full max-h-[250px]" /> */}
              <main>
                {children}
              </main>
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
